[project]
name = "transcription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.56.0",
    "pymupdf>=1.26.7",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
